### ISSUE TITLE
CANVIS -- AttributeError: 'NoneType' object has no attribute 'get_texts'

### ISSUE THREAD

**Issue by CScottG** [gkichaev/PAINTOR_V3.0#10]
Hi, when trying to run the sample files for CANVIS either through inputting the command directly or doing 'bash run_canvis.sh' from the sample folder I get the error pasted below:

phss-imac-2:CANvis_Sample $ bash run_canvis.sh 
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py:4747: UserWarning: No labeled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labeled objects found. "
Traceback (most recent call last):
  File "CANVIS.py", line 518, in <module>
    main()
  File "CANVIS.py", line 492, in main
    zscore_plots = Plot_Statistic_Value(location, zscores, zscore_names, greyscale, ld)
  File "CANVIS.py", line 162, in Plot_Statistic_Value
    for label in legend.get_texts():
AttributeError: 'NoneType' object has no attribute 'get_texts'

**Please let me know if you have any thoughts on what is causing the error and/or how to maybe fix it.

**Comment by ruthjohnson95** [comment]
Hello,
That's interesting that it won't run the sample data with the test script that was included. None of the script or data was changed, correct? 

I wonder if the versions of the libraries are up to date? Specifically, older versions of matplotlib 1.X.X are not compatible with generating the figures correctly. I will include the required version number in the wiki as well for future reference. Additionally, I had pushed a few changes to CANVIS ~1 month ago, so I'd re-pull the CANVIS folder if you initially cloned it before April. 

Python - 2.7 
matplotlib - 2.0.0
pandas - 0.15.2
numpy - 1.12.0
seaborn - 0.7.1
scipy - 0.15.1

Hope this helps, but let me know how it goes!

**Comment by ruthjohnson95** [comment]
Hello,

Another user emailed me regarding the same issue. We found that the solution the error listed above is to update the matplotlib library to version 2.0.0 or higher. 
Many versions are still 1.X.X, but 2.0.0 was a somewhat recent major release that makes it incompatible with certain plotting functions of previous versions.
