### ISSUE TITLE
Computation of credible set

### ISSUE THREAD

**Issue by MichelNivard** [gkichaev/PAINTOR_V3.0#12]
This may be blindingly obvious, but I could not find the way in which you compute the XX% credible set.

Is it the smallest set with a cumulative sum of posterior probabilites which is XX% of the total sum of posterior probabilities?

Best,
Michel

**Comment by ruthjohnson95** [comment]
Yes, exactly! 

In the code, we rank all of the SNPs by their calculated posterior probability and then add to a set until the cumulative probability of the set is equal to the (XX%)*(total posterior prob), which is what you mentioned above.
