### ISSUE TITLE
how to getZ-scores

### ISSUE THREAD

**Issue by lantianbaiyunrui** [gkichaev/PAINTOR_V3.0#13]
Hi,
    I am appreciated using this software to complete  my program.
    However, my gwas data does not include Z-scores, may I convert P-value to Z-scores, using this formula (p-mean(p))/sd(p), could you give me some suggestions.
    Thank you very much!
    All best!
     rui

**Comment by gkichaev** [comment]
Hi Rui,

I'm not sure what p in your formula represents? Is that the p-value? I'm not familiar with that transformation.

What you could do is invert the p-value to Zscore using the "qnorm" command in R. However, you will need the sign of the Z-scores. If those are unavailable to you, then you will not be able to run the software.

Gleb

**Comment by lantianbaiyunrui** [comment]
hi gkichaev,
 thank you for your response, I can try it 1
