### ISSUE TITLE
Segmentation fault when using PAINTOR with different annotaions

### ISSUE THREAD

**Issue by xiaoyu610** [gkichaev/PAINTOR_V3.0#14]
Hi,

Recently, when I'm running PAINTOR, it fails to recognize the last column  head in my annotation file. And it shows:

Error: Annotation INTRON not found in annotation file
Segmentation fault

However, all columns in my annotation file are in the same data frame. I don't why this happened.

Thank you!

Xiaoyu

**Comment by gkichaev** [comment]
It could be a number of things. Could you provide the command line you used to execute the program and the first few lines of your annotation file?

**Comment by xiaoyu610** [comment]
Sure, my commend line is:
PAINTOR -input input_file.txt -Zhead zscore -LDname ld -in ./ -out ./ -annotations INTRON -Gname Enrich.in -Lname BF.in

annotation file is: (for each locus)
CODING UTR PROMOTER DHS INTRON
0 0 0 0 1
0 0 0 0 1
0 0 0 1 0
0 0 0 0 0
0 0 0 0 0

Really thank you for quick response.

**Comment by gkichaev** [comment]
Interesting. That looks correct. Are you using the "\n" escape sequence to indicate a newline. Perhaps that's the problem. A quick hack could be to add a column of a dummy annotation to rule that out.

**Comment by xiaoyu610** [comment]
Great, your method works. And I found this problem only appears on the last column of my annotation matrix. I'm using r to create my annotation matrix, maybe "\n" is inbuilt in R. Anyway, thank you so much for your help.

-Xiaoyu
