### ISSUE TITLE
AT GC SNPs in the Calc LD companion script

### ISSUE THREAD

**Issue by vlaufer** [gkichaev/PAINTOR_V3.0#15]
Hello,

In the CheckLD companion script, there is a step that drops AT and GC SNPs.

I have data the strand of which either is known or can be determined across all studies, even for AT and GC SNPs. I also have MAF information, so I can drop AT and GC SNPs if MAF is close to 0.5 to aid with this.

My question is, do you have a version of the CheckLD script that does not drop AT and GC SNPs that you used in the past? If yes, would it be possible to obtain the code? If no, but you have done this, do you have any guidance? This is an extra step I am taking on to get *more* accurate fine mapping, I understand the issues with these SNPs and I know they can be tricky ... I definitely do not want to *decrease* accuracy in an extra step but rather the reverse.

**Comment by vlaufer** [comment]
Also, I appreciate this is not a true Github issue. If you prefer email please let me know.

VL

**Comment by gkichaev** [comment]
Hey Vincent,

Unfortunately the script that's provided does not have functionality to match on strand. Conceivably, you could comment out the line of code that drops the SNPs -- though I've never done this myself. 

I'm not aware if the 1000 genomes provides strand information.

**Comment by vlaufer** [comment]
@gkichaev Hi Gleb-  I am modifying the CalcLD script a bit to get a bit more data back. 

I am curious as to why the function Match_Ref_Panel_Alleles() is defined twice. Could you comment on that?

**Comment by gkichaev** [comment]
Good catch. The function on line 94 is redundant. I'll remove it. Thanks!
