### ISSUE TITLE
Error with Z-score header

### ISSUE THREAD

**Issue by jfertaj** [gkichaev/PAINTOR_V3.0#20]
Hi I am trying to run PAiNTOR in a single locus but I got the following error

```
Reading in files for: TANC1
Reading in files for: 
Error! Specified Z-score headers not found in locus file
Terminating Execution
```

my command line is the following
`./PAINTOR -input RunDirectory/input.file -Zhead ZSCORE.P1 -LDname LD -in RunDirectory/ -out OutDirectory/ -enumerate 2 -Gname Enrich.Base -Lname BF.Base`

And hera a few lines of my locus file

```CHR BEGIN A1 A2 SNP ZSCORE.P1
2 159819408 T G rs78148102 1.92042940261
2 159819716 G A rs4664266 -1.40671281391
2 159819869 T G rs55725300 0.703711991248
2 159821451 A G rs77227230 -5.5365023986
2 159822081 G A rs115029554 0.231168715877
2 159823927 A G rs842075 -1.62239868565
2 159824573 T C rs842073 -1.92313770562
2 159825201 G A rs555930586 -0.254509018036
2 159825320 C T rs62182242 -0.709404418828```

**Comment by gkichaev** [comment]
You need a header in your locus file. So in your case, the first line of your file should be
"Chr Pos A1 A2 SNP ZSCORE.P1"

**Comment by jfertaj** [comment]
Sorry @gkichaev but I didn't copy the header, my header look like this:
```
head RunDirectory/TANC1
CHR BEGIN A1 A2 SNP ZSCORE.P1
2 159819408 T G rs78148102 1.92042940261
2 159819716 G A rs4664266 -1.40671281391
2 159819869 T G rs55725300 0.703711991248
2 159821451 A G rs77227230 -5.5365023986
2 159822081 G A rs115029554 0.231168715877
2 159823927 A G rs842075 -1.62239868565
2 159824573 T C rs842073 -1.92313770562
2 159825201 G A rs555930586 -0.254509018036
2 159825320 C T rs62182242 -0.709404418828
```

**Comment by gkichaev** [comment]
is your input.file correct? I think you may have an extra line at the end. Try removing it.

**Comment by jfertaj** [comment]
Hi @gkichaev, I have removed any extra line at the end but it stills drops the same error, I have attached my locus file
[TANC1.txt](https://github.com/gkichaev/PAINTOR_V3.0/files/1561018/TANC1.txt)

**Comment by gkichaev** [comment]
That's strange. I'm not sure. Maybe try changing "ZSCORE.P1" to "Z"
