### ISSUE TITLE
Name of annotations

### ISSUE THREAD

**Issue by jfertaj** [gkichaev/PAINTOR_V3.0#22]
Hi,

I have overlapped my locus with all the Functional_annotations available, and the `annotations` file has as header the name of the bed file. When running the command I got an `Segmentation fault` error, could it be due to the long names of annotations?

Example of command line

`./PAINTOR -input input.file -Zhead ZSCORE.P1 -LDname LD -in RunDirectory/ -out OutDirectory/ -enumerate 2 -annotations ZEB1.bed  -Gname Enrich.ZEB1.bed -Lname BF.ZEB1.bed`

**Comment by gkichaev** [comment]
Does your annotation file have the "annotations" suffix?

**Comment by jfertaj** [comment]
It was a problem with the path of input file, if the Enrich result files are 0, does it mean that I have no enrichment and that baseline model hasn't been improved right?
