### ISSUE TITLE
LD calculation

### ISSUE THREAD

**Issue by alessandrotestori** [gkichaev/PAINTOR_V3.0#3]
CalcLD_1KG_VCF.py can generate an LD matrix file, which is then fed to PAINTOR. Is it possible to have the first lines of sample files which are the input to CalcLD_1KG_VCF.py? What is the format of the the "Map file", i.e. the .panel file that has sample and population id's?
Does the square root of r^2 LD values correspond to the absolute value of Pearson correlation coefficients?

**Comment by gkichaev** [comment]
Hi Alessandro,

In section 2a of the wiki I provide a link to where the 1000 genomes reference LD file can be downloaded. There you will find a file called "integrated_call_samples_v3.20130502.ALL.panel". This is what I refer to as the "Map file". 

Mathematically, yes the square root of r^2 the corresponds to the absolute value of the Pearson correlation. However, for PAINTOR analysis, the sign of the correlation is vitally important. The CalcLD_1KG_VCF.py utility will compute signed person correlations that are polarized relative to the reference and alternate alleles of your data. 

Best,
Gleb

**Comment by alessandrotestori** [comment]
After launching CalcLD_1KG_VCF.py, the pointer of my mouse becomes a cross and I can no longer use it.

**Comment by gkichaev** [comment]
hmmm.. you may be running out of memory, though there's really nothing that memory intensive about the computation.  Unless, however, you are trying to compute LD for 10's of thousands of SNPs -- I advise against this. 

You can try computing LD using plink 2. Take care to match the reference and alternate alleles though. 

-G

**Comment by alessandrotestori** [comment]
Thanks Gleb. The vcf file must be compressed (.vcf.gz)?

**Comment by gkichaev** [comment]
Yes, the VCF must be compressed. Lack of disk space may have something to do with your problem.

Just a heads up, PAINTOR analysis may be hard to run unless you have access to a compute cluster as it could take hours to days to execute, depending on how many regions you are fine-mapping.

**Comment by alessandrotestori** [comment]
I have found that CalcLD_1KG_VCF.py works fine on Mac, but I cannot make it work on ubuntu. However a lot of SNPs are discarded, since I get the following error message:
Ambiguous SNP (AT or CG) in input locus. Dropping row ...
I would like to compute the r value for all SNPs: how can I do? Please let me know.

**Comment by gkichaev** [comment]
Yes, we discard ambiguous SNPs because it is impossible to correctly infer the sign of the correlation without also knowing the positive and negative strand labels. For example, and AA on the positive strand is equivalent to a TT on the negative strand due to Watson-Crick base pairing.

I would advise against using these SNPs. But if you need them for non-PAINTOR analysis then a quick hack would be to replace lines 30&31 of the code with lines 33&34. 

If you are unable to attribute the sign, then you are limited to running the model with a single causal variant as the LD cancels out when probabilities are normalized. The results will not be valid if you want to consider more complex models.

**Comment by alessandrotestori** [comment]
Hi Gleb, besides discarding ambiguous SNPs (several are of interest for me),  CalcLD_1KG_VCF.py gives the following error:
File "CalcLD_1KG_VCF.py", line 266, in <module>
   if __name__ == "__main__": main()
File "CalcLD_1KG_VCF.py", line 257, in main
   [vcf_rows, found_positions] = Filter_VCF_rows(reference, all_positions)
File "CalcLD_1KG_VCF.py", line 54, in Filter_VCF_rows
   max_position = max(pos)
ValueError: max() arg is an empty sequence

Please tell me what I should do with this!
Thanks, regards.

**Comment by gkichaev** [comment]
I'm not really sure. That's the first time I've seen that error. Are you sure your input files are formatted correctly?

**Comment by vlaufer** [comment]
@alessandrotestori - did you accidentally specify a chromosome start position greater than the end position? This would result in the error you describe above. Alternatively, are you sure your source file contains SNPs in the region specified? Perhaps provide a snippet of the file you are inputting into the CalcLD script.

**Comment by alessandrotestori** [comment]
Is it possible that the error is due to the fact that my locus file has only one SNP? In fact my locus file looks like this:

CHR POS SNP_ID EFFECT_ALLELE ALTERNATIVE_ALLELE Zscore
chr1 19407771 rs16862514 a g 2.66

If so, I will ignore it
##########################################################

Unfortunately I also have another error:

terminate called after throwing an instance of 'std::runtime_error'
  what():  nlopt failure
Aborted (core dumped)

PAINTOR terminates after the first iteration and I'm not able to understand why. In this case, I'm using annotations.

**Comment by vlaufer** [comment]
@alessandrotestori - yes this is the problem. Because PAINTOR uses the relationships between many SNPs to perform the variant prioritization, making a locus file with only 1 variant will not be meaningful (the top SNP in a list of 1 SNP is always just that SNP). In addition, it is likely to result in errors like the one you describe above as well.

However, above you have said that many of your SNPs have been discarded as ambiguous. How many did you have to begin with, how many were discarded, (and only one remains, correct?).

You would have to ask Gleb this, but I suspect the optimal number of SNPs in the locus is somewhere in the neighborhood of 100-1500.

**Comment by gkichaev** [comment]
Yes, @vlaufer is correct in his diagnosis. Thanks!

**Comment by alessandrotestori** [comment]
I really have no idea about this error:

terminate called after throwing an instance of 'std::runtime_error'
what(): nlopt failure
Aborted (core dumped)

I've tried hard for hours to figure it out. However I will open a new issue

**Comment by vlaufer** [comment]
I was not necessarily asking you to do that, I was just trying to ask does this error happen in the same analysis as the prior error, or a different one?

**Comment by alessandrotestori** [comment]
That is an error in a different analysis. Sorry for having generated confusion about that!

**Comment by xiaoyu610** [comment]
Hi,
I'm a little confused about the notation of alleles in LD calculation. So the (2) effect allele means the alternative allele in my data which contributes to z-score and (3) alternative allele is the reference allele in the usual data set? The confusion part is that usually I use reference allele and alternative allele to represent the two alleles. Alternative allele usually is the one with z-score. Am I correct? Thanks.

Best,
Xiaoyu

**Comment by gkichaev** [comment]
Hi @xiaoyu610, yes the terminology is a bit vague.  What I mean by the effect allele is the one that is encoded as "1" in your data. The alternative allele is the one encoded as "0".

--Gleb

**Comment by xiaoyu610** [comment]
OK, I got this one. Thank you Gleb for your clear reply!
