### ISSUE TITLE
Running CalcLD for multiple ethnicites in the same locus results in non identical .processed files

### ISSUE THREAD

**Issue by vlaufer** [gkichaev/PAINTOR_V3.0#4]
I ran the command 

```
        for ETH in "${ETH_ARRAY[@]}"; do
                if [ ! -f ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_${ETH}_LOCUS ]; then
                        python $COMPANION_SCRIPT_DIR/CalcLD_1KG_VCF.py \
-l ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_Source \
-r $ONE_KG_DIR/ALL.chr${CHR}.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz \
-m $ONE_KG_DIR/integrated_call_samples_v3.20130502.ALL.panel \
-i "POS" \
-e "EFFECT_ALLELE" \
-a "ALT_ALLELE" \
-p $ETH \
-z ZSCORE.$ETH \
-o ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_${ETH}
                        mv ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_${ETH}.processed ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_${ETH}
                fi

        done
```

which runs the CalcLD_1KG_VCF.py script for one and the same locus N times, where N is equivalent to the number of ethnicities in the ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_Source file. This command writes N .ld and .processed files. 

However, examination of the resulting .processed files using the diff command in linux shows a consistent inconsistency in assignment of sign to the Z scores, like so:

```
diff 2_204575000_204825000_EUR 2_204575000_204825000_EAS
2c2
< chr2 204575951 rs1181388 A G 0.462446668093 0.0 -0.970199346545
---
> chr2 204575951 rs1181388 A G 0.462446668093 -0.0 0.970199346545
5c5
< chr2 204577559 rs7426281 A G 0.144381262161 -1.58748108105 2.78890373918
---
> chr2 204577559 rs7426281 A G 0.144381262161 1.58748108105 -2.78890373918
7,9c7,9
< chr2 204578797 rs3769683 A G 0.967471356768 -0.380099034782 -0.970199346545
< chr2 204581195 rs17533594 A G -0.402092856399 -1.39747290952 2.78890373918
< chr2 204582679 rs10515943 T C -0.34572574725 -1.39747290952 2.78890373918
---
> chr2 204578797 rs3769683 A G 0.967471356768 0.380099034782 0.970199346545
> chr2 204581195 rs17533594 A G -0.402092856399 1.39747290952 -2.78890373918
> chr2 204582679 rs10515943 T C -0.34572574725 1.39747290952 -2.78890373918
11,12c11,12
```

Because the differing Z score assignments are always exactly inverse (at least in the scans I have done), I am not sure that anything needs to be done at all. However, as you note in the PAINTOR3 wiki, assignment of the sign for each Z stat in reference to the effect and alt allele is vitally important for correct function of fastPAINTOR, so I wanted to be positive.

Finally, I want to note that the _EUR and _EAS files refer to the output from the meta analysis of RA written by Okada et al., so I know you are familiar with the dataset.

If you would like, I can remove the AFR data and run CalcLD again only on this meta analysis data. It is well curated so it should be a good test case.

**Comment by vlaufer** [comment]
It just occurred to me the solution is probably to take all 3 .processed files, and use ONLY the ZSCORE.${ETH} column from each ${TARG}/${CHR}_${STARTPOS}_${ENDPOS}_${ETH} file to write a final output file, ignoring the other two ZSCORE columns from each output file.

**Comment by gkichaev** [comment]
Hi Vincent,

Yes I think you got it. Apologies for how crude the script is. I think you just need to extract the columns from the corresponding .processed file and everything should be good.

As it stands, I don't think the code will be able to execute in the manner in which you described for multiple populations -- but it may be a good idea to add this functionality at some point in time,. 

Good luck!

-Gleb

**Comment by vlaufer** [comment]
Got it. Thank you so much for your help and feedback. And the awesome code.
