### ISSUE TITLE
All Posterior_Prob are 0 when running PAINTOR without any annotations 

### ISSUE THREAD

**Issue by skanoni** [gkichaev/PAINTOR_V3.0#5]
Hi, I am trying to run PAINTOR on small FM regions (~2000 variants) with dummy annotation files (0). When I get the results all Posterior_Prob are 0. I am not sure why this happening. I would appreciate some help. Thank you.

**Comment by gkichaev** [comment]
That's a bit strange. Are you sure your files are formatted correctly?

**Comment by snlent** [comment]
I see this issue was closed, but what was the resolution? I'm having the same problem. When I use a dummy annotation file and -enumerate k everything works fine, but when I use a dummy annotation file and -mcmc, all posterior probabilities are 0.

**Comment by lisongmiller** [comment]
Same here. I use AnnotateLocus.py to generate annotation file first, but all the annotations are 0.  Then I thought just use this annotation file as dummy, use paintor -mcmc option, then every SNP in the results file with Posterior_Prob as 0. Any solutions for this?

**Comment by cindywen96** [comment]
I see the issue has been closed but is there an answer? I am having the same problem here. Some of my loci have all 0 PIP, while others look fine.

**Comment by skanoni** [comment]
Hi,

If I remember correctly I managed to resolved that by first filtering out all NAs from the LD matrix. I hope it helps.
________________________________

**Comment by lanshanxuying** [comment]
> I see the issue has been closed but is there an answer? I am having the same problem here. Some of my loci have all 0 PIP, while others look fine.

I have the same issue like you . Did you solve this problem at last ? My LD matrix doesn't have any NAs.
