### ISSUE TITLE
What steps should I follow if I am receiving an "optimization error encountered" message

### ISSUE THREAD

**Issue by vlaufer** [gkichaev/PAINTOR_V3.0#7]
Dear Gleb,

I am running PAINTOR3 now. I ran it on a test locus and it ran fine, but when I ran it on the full locus, the output looks like this:
```
E004_15_coreMarks_mnemonics.bed.13_ReprPC.H1_BMP4_Derived_Mesendoderm_Cultured_Cells
Reading in files for: CLEAR_Okada_2_204575000_204825000
Running PAINTOR with full enumeration of a maximum of 2 causals per locus
Sum of log Bayes Factors at iteration 0: 22.95511
Parameter Estimates:
5.03370062
         0

Optimization error encountered 
5.03370062
         0
Sum of log Bayes Factors at iteration 1: 23.3430293
Parameter Estimates:
5.03370062
         0

Optimization error encountered 
5.03370062
         0
Sum of log Bayes Factors at iteration 2: 23.3430293
Parameter Estimates:
5.03370062
         0
```

This is in the context of running the model for one annotation at a time, so I can get the marginal distribution for each annotation. 

For some annotations, I get the output above, for other annotations, I do not. specifically, when the second parameter is 0, it issues the error, else, it does not. My question is, is this error potentially something I need to be concerned about, or would it be safe to just throw out those annotations and continue with the ones for which that error was not issued? Even more so do you know what kind of error this could be, and what I should do to track it down?

Kind Regards,

VIncent

**Comment by gkichaev** [comment]
Hi Vincent,

Yes this occurs seemingly at random for certain annotations. I haven't quite dialed in precisely what causes this instability as the optimization routines that I am using in the software throw a generic error message when they fail. In previous versions of PAINTOR the program would just crash, now I through an error message and attempt to re-optimize it. Sometimes this works, other times it doesn't. Looks like in this case you are in the latter category. 

I suspect that this isn't something that will effect your final analysis tremendously. You can safely ignore it. 

--G

**Comment by vlaufer** [comment]
OK - My solution will be to throw out the annotations for which this occurs, for now. If I am able to discern any pattern, I will post it here. 

Since this seems to be a problem you are dialing down, I'll leave the issue open for now and add if I get more info.

VL
