### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MichelNivard** [gkichaev/PAINTOR_V3.0#9]
Hi I installed, and reinstalled, PAINTOR V3.0 executing it results in a segmentation fault 

exact message:

"Segmentation fault (core dumped)"

exact command executed:
./PAINTOR -input ld_out.SZ.processed -Gname SZ Lname BSZ -out paintor_output/ -in SZ_Data/ -Zhead Zscore -LDname ld_out.SZ.ld

Any suggestions of how to proceed?

Best,
Michel Nivard

**Comment by MichelNivard** [comment]
Some additional info, the example data does run, and the data I provide to PAINTOR is processed withthe python tool which computes the LD matrix

**Comment by vlaufer** [comment]
@MichelNivard  you lack a hyphen before -Lname, which causes C to improperly parse arguments, resulting in a segmentation fault

**Comment by MichelNivard** [comment]
Thanks for the quick reply!

Unfortunately this doesn't seem to be the (only) issue. I Tried many configurations landing on:

./PAINTOR -input input.files -in SZ_EA_Data/ -out paintor_out/  -LDname ld -Zhead Zscore

This and all other attempts except for the demo code fail with a segmentation fault...

**Comment by vlaufer** [comment]
Unfortunately its going to be pretty difficult for anyone but you to trouble shoot a problem like this. From afar, all I can do is make suggestions, for instance, "have you double checked all the file paths" or "are you positive the column headings in each input file are correct?"

I hope the prior comment gives you some insight, though, into the meaning of the error itself..

**Comment by MichelNivard** [comment]
Thanks, I solved it,tyhe error was indeed caused by a misspecified path.

**Comment by vlaufer** [comment]
@MichelNivard great! unless you or Gleb needs to weigh in I would recommend closing the issue.

**Comment by gkichaev** [comment]
Many thanks for the helping debug the problem @vlaufer. I thought I added a check to ensure that all the input files were correctly specified. Will look into this to make sure.
